# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY src ./src
COPY README.md ./README.md

# Install dependencies and the MCP server
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Default entrypoint for the MCP server
ENTRYPOINT ["oceanbase_mcp_server"]
